[theme]
primaryColor = "#9b51e0"
backgroundColor = "#03001e"
secondaryBackgroundColor = "#0a0c1e"
textColor = "#f3f4f6"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
